drop table cinemas CASCADE CONSTRAINTS;
drop table movies CASCADE CONSTRAINTS;
drop table rooms CASCADE CONSTRAINTS;
drop table users CASCADE CONSTRAINTS;
drop table seats CASCADE CONSTRAINTS;
drop table MovieCategories CASCADE CONSTRAINTS;
drop table Schedules CASCADE CONSTRAINTS;
drop table Tickets;
drop table Purchases CASCADE CONSTRAINTS;
drop table TicketTypes;
drop table TicketHistory;
drop table MovieHistory;
commit;